### PR TITLE
Use Unicode case folding instead of `lower()` if available

### PR DESCRIPTION
**Pull request by rudolfbyker**
Issue #3

### CODE REVIEW

**Comment by coldfix** [comment]
Hi,

thanks! Using `casefold` makes sense! I didn't even know about it.

There is still some tests failing, but I didn't look into it in more detail. My first guess would be it is due to python2 having `str` being alias for `bytes` but being different from `unicode` -> which means that `_fold(u'oeie')` might not do its job, in your implementation (previous implementation used attribute access, yours uses the `str` method explicitly)

**Comment by coldfix** [comment]
Also, the new `_fold` can't handle `bytes` types on python3.

I guess itshould technically look like this:

```
def _lower(s):
    try:
        return s.casefold()
    except AttributeError:
        try:
            return s.lower()
        except AttributeError:
            return s
```

**Comment by coldfix** [comment]
I suggest that `_lower` becomes an argument of `_make_dicti` and `build_dicti`, so that users can theoretically choose what comparison to use (even non-string types), but that could be done in a later patch (I can do it if you don't have time).

Also, I'd prefer to keep the name `_lower` for now, it's clearer IMO (and whether `casefold` or `lower` is used under the hood is an implementation detail that doesn't need to be reflected in the name choice here).

**Comment by rudolfbyker** [comment]
> def _lower(s):
>     try:
>         return s.casefold()
>     except AttributeError:
>         try:
>             return s.lower()
>         except AttributeError:
>             return s

I thought of doing it like this, but I think it might be more performant to detect the proper method when importing the module, rather than every time a dict key is accessed. Tricky...

> Also, I'd prefer to keep the name `_lower` for now, it's clearer IMO

A matter of taste, I guess. :)

-----

OK, I'll have another go at this!

**Comment by coldfix** [comment]
> I thought of doing it like this, but I think it might be more performant to detect the proper method when importing the module, rather than every time a dict key is accessed. Tricky...

Yes, I had the same feeling (although didn't measure it). That's why I had the idea to make `_lower` a parameter, so that users can theoretically choose a method that's well adapted to their specific use case.

**Comment by coldfix** [comment]
Awesome, thanks!

**Comment by coldfix** [comment]
FYI, I have added the option to let the user parametrize using a custom normalization function and renamed it to `normalize` (instead of `_lower`, which is admittedly not the best name either).

**Comment by rudolfbyker** [comment]
Very nice! Normalize is a good name.

**Pull request merged**
